### ISSUE TITLE
handler is not a function 

### ISSUE THREAD

**Issue by emersonlaurentino** [telegraf/micro-bot#14]
when I do deploy in now.sh and squeeze any command, it returns me an error: handler is not a function

https://github.com/telegraf/micro-bot#advanced-examples

**Comment by amir-hossein-zarei** [comment]
how do you solve your problem?

**Comment by emersonlaurentino** [comment]
I was implementing it wrong, so I used the micro-bot.

**Comment by amir-hossein-zarei** [comment]
can you help me?
`μ-bot: Unhandled error TypeError: handler is not a function`
this is my code:
`const { readFileSync } = require('fs')
const { Composer } = require('micro-bot')
var HttpsProxyAgent = require('https-proxy-agent');
const app = new Composer()

app.start((ctx) => ctx.reply('Welcome ${ctx.message}'))
app.help((ctx) => ctx.reply('Help message'))
app.hears('hi', ({ reply }) => reply('Hello'))
app.on('sticker', ({ reply }) => reply('👍'))

// Export bot handler
module.exports = app
module.exports = {options: {telegram: {agent: new HttpsProxyAgent('http://127.0.0.1:3503')}}}`

**Comment by amir-hossein-zarei** [comment]
what do you mean?
please, help :(
