### ISSUE TITLE
fetching Bot info from telegram

### ISSUE THREAD

**Issue by shrynx** [telegraf/micro-bot#3]
Hi !
Thanks for making telegraf and micro bot, makes bot development extremely simple.
i have one issue, i am not sure how to get **botInfo** (the one from `telegram.getInfo()`).
I don't want to instantiate telegram again as it is automatically done by microbot.

It would be extremely helpful if i could access it from micro-bot.

```javascript
const { Composer, botInfo } = require('micro-bot');
```
If this is valuable for you, i will try making a PR for it.

**Comment by dotcypress** [comment]
Hey.

Thank you for feedback! 👍 

From version `1.3.2` you can [obtain bot info from update context](https://github.com/telegraf/micro-bot#telegraf-context).

**Comment by shrynx** [comment]
i was looking at docs and wondering how i missed it !
Haha, this just happened today !

**Comment by dotcypress** [comment]
Brand new feature 😎
