### ISSUE TITLE
Loading enviroment variables

### ISSUE THREAD

**Issue by manzanit0** [telegraf/micro-bot#4]
Hi,

I was wondering how can I load the environment variables from a file using `dotenv` or any other package. This is because even though I load them before even requiring the`micro-bot` module, it won't let me:

`μ-bot: Please supply Bot token`

Is it possible to do this? I tried with the following code while having a `.env` file in the root directory with the `BOT_TOKEN`:

```
'use strict';

// Configure enviroment variables.
require('dotenv').config();

console.log(process.env.BOT_TOKEN);

// Telegraf based framework.
const { Composer } = require('micro-bot');
const app = new Composer();
```

Thanks.

**Comment by dotcypress** [comment]
Hi,

Actually you must set environment variables before starting `micro-bot` script.
Example: `source .env & npm run dev`

**Comment by dotcypress** [comment]
New version of `micro-bot` now supports `-e` flag.
