### ISSUE TITLE
Unable to start smart-bot from example in readme.md

### ISSUE THREAD

**Issue by ghost** [telegraf/micro-bot#6]
Hi,
Thanks for making micro-bot, this looks like a really cool project! I am having some trouble getting it started, however.

I went through the readme.md instructions, but when I try to run the bot, the following happens:

```
$ BOT_TOKEN=<token> npm start

> smart-bot@1.0.0 start /home/ubuntu/smart-bot
> micro-bot

μ-bot :: Starting @OpenFaasYoutubeBot
μ-bot: Failed to start bot: TypeError: function resolve() { [native code] } called on non-object
$ micro-bot -t <token> index.js 
micro-bot: command not found
```

my package.json looks like:
```
{
  "name": "smart-bot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "micro-bot"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "micro-bot": "^1.4.0"
  }
}
```

And this is deployed on a machine which is exposed to the internet, so the telegram API should be able to reach it.

Thanks in advance for any help!
-Eric

**Comment by dotcypress** [comment]
Hey @ericstoekl , thank you for report.

Fix published in `v1.4.1`
