### ISSUE TITLE
bot.hears(...) doesn't work in group chats

### ISSUE THREAD

**Issue by koddsson** [telegraf/micro-bot#7]
I'm basically having the same issue as https://github.com/telegraf/telegraf/issues/134 but it looks like `micro-bot` already sets the username?

**Comment by dotcypress** [comment]
Yes, but username only  needed for command handling.
`hears` should work in group chats, but make sure that bot [privacy mode](https://core.telegram.org/bots#privacy-mode) is switched off and bot have all permissions in chat.
